### ISSUE TITLE
[BUG] [T6] Most vectors cause server to hang when used as an argument in a function

### ISSUE THREAD

**Issue by INSANEMODE** [xensik/gsc-tool#33]
The issue occurs when using release 1.0.347 25f20d8 (or previous), to compile a t6 script.

When running the script below, in a plutonium t6 zm server, the server will hang, similar to if it is in an infinite loop. 
Execution halts immediately after a function with a vector as an argument is called 3 times. 

Problem does not occur if vector contains only the values -1, 0, 0.0, or 1 in each place. 

I have not tested to see if this affects scripts loaded on the t6 zm client, or t6 mp.

Example script to reproduce issue:
```gsc
#include common_scripts\utility;
#include maps\mp\zombies\_zm_utility;

init()
{
	onplayerconnect_callback(::onPlayerConnect_test);
}


onPlayerConnect_test()
{
	level endon( "end_game" );
	self endon( "disconnect" );
	self thread vector_test();
}

test_function_2(vector)
{
	iprintln("test_function_2 called");
	//iprintln("vector: " + vector);
}

vector_test()
{
	level endon( "end_game" );
	self endon("disconnect");

	while(1)
	{
		if(self useButtonPressed())
		{


			vector = (60,0,0); //if any of these values are anything other than -1, 0, 1, or, 0.0 the server will hang on the third time the function with a vector as an argument is called.

            
			//self scripts\zm\crash_test::test_function_2(vector); //crash
			//self test_function_2(vector); //crash
			//scripts\zm\crash_test::test_function_2(vector); //crash
			//self scripts\zm\crash_test::test_function_2((1,0,.2)); //crash
			//test_function_2(vector); // crash
			iprintln("vector: " + vector); //crash
		}
		wait 0.1;
	}
}
```

**Comment by xensik** [comment]
can you try using an expresion? example
```
vector = (60 + 4,0,0);
```
if values are 1, -1, 0 uses opcode VectorConstant
if values are all numbers uses opcode GetVector (values placed after opcode)
if values contain expressions uses opcode Vector (pull 3 values from stack)

**Comment by INSANEMODE** [comment]
Sure, I can do that. Leaving for work now, but can do this when I get off.

**Comment by INSANEMODE** [comment]
> can you try using an expresion? example
> 
> ```
> vector = (60 + 4,0,0);
> ```
> 
> if values are 1, -1, 0 uses opcode VectorConstant if values are all numbers uses opcode GetVector (values placed after opcode) if values contain expressions uses opcode Vector (pull 3 values from stack)

yep, doing this works correctly. 
![image](https://user-images.githubusercontent.com/10606102/193395731-dc9efd19-27a7-4d48-81eb-40a4f4f373aa.png)

**Comment by xensik** [comment]
so its a problem only for OP_GetVector. i will take a look in the engine since compiler seems fine

**Comment by mjkzy** [comment]
i think this is related to what i sent you monthssss ago xensik.
![image](https://user-images.githubusercontent.com/64374267/193482724-3df0ff38-e05a-4dec-b100-f9b56bbb7b50.png)
![image](https://user-images.githubusercontent.com/64374267/193482725-17d70c7f-72ab-4c27-b940-4ecb7050a05b.png)

**Comment by xensik** [comment]
seems like original scripts dont have a single OP_GetVector instruction. maybe is broken in the engine.
Im going to change the impl to always use OP_Vector

**Comment by ineedbots** [comment]
This occurs because of 3arc adding alignment to their bytecode.

![image](https://github.com/user-attachments/assets/0c7913dc-35e7-41c7-bce0-30d96b80e55c)

As you can see, it aligns to a double word;

![image](https://github.com/user-attachments/assets/69d12d09-60b3-451b-a5f4-b7c0d11797d5)

![image](https://github.com/user-attachments/assets/fe220482-632b-4d18-806a-724196e88ff9)



you can see here that inside of RemoveRefToVector, they are checking the highbyte BEFORE the vector pointer if it is zero or not, if it is zero, the vector is part of the memtree and needs to be cleaned up, which is wrong because the vector resides in the bytecode, not MT.


IW vm doesnt have this issue because of no alignment;
![image](https://github.com/user-attachments/assets/8001d032-add8-4e05-a809-33c8c6845b6d)

![image](https://github.com/user-attachments/assets/416276d0-5c3e-410e-a0df-753a865a29e0)

![image](https://github.com/user-attachments/assets/a8db2f17-7744-411f-bdf0-19210f0d8f6e)

As you can see, the high byte of the RefVector head is the `byteLen`. normally this is supposed to be 0xC (the GetVector opcode).  But in 3arc, its align filled with 0s.
